### ISSUE TITLE
What is IDE used to  dev them?

### ISSUE THREAD

**Issue by hungcuiga1** [santiagobaronz/oasis-webcore#1]
Hello, i am a newbie, can you tell me software used to dev your project. Thank you so much!

**Comment by santiagobaronz** [comment]
Hi! Yes, no worries. In order to develop this project I used my favorite IDE Visual Studio Code and regarding technologies: HTML5, CSS3 and Javascript. This project is currently stopped but hopefully I'll be working again using react and tailwind. Let me know if you have more doubts. Have a great day!

**Comment by hungcuiga1** [comment]
Thank you so much
